### ISSUE TITLE
Rivedere la pianificazione per la fase corrente

### ISSUE THREAD

**Issue by danielcontro** [Spaghetti-Code-G6/swe-docs#10]
## Descrizione:

Specificare più finemente la pianificazione temporale della fase corrente, facendo emergere maggiormente il modello di sviluppo incrementale

**Comment by Archetipo95** [comment]
Ci sto lavorando. Ho cambiato programma per fare i diagrammi di Gantt [Grantt project](https://www.ganttproject.biz/download/gp30)

Cose da fare:
- [ ] Trascrivere dati _Analisi_ su nuovo diagramma (senza modifiche?)
- [ ] Trascrivere dati _Consolidamento dei Requisiti_ su nuovo diagramma (senza modifiche?)
- [ ] Creare nuovo diagramma di Gantt per _Progettazione Architetturale_
- [ ] Creare nuovo diagramma di Gantt per _Progettazione di Dettaglio e Codifica_
- [ ] Creare nuovo diagramma di Gantt per _Validazione e Collaudo_
