### ISSUE TITLE
Definizione test di sistema

### ISSUE THREAD

**Issue by rizzostefano** [Spaghetti-Code-G6/swe-docs#101]
Sei diventato il signore oscuro della verifica. Tocca a te decidere quali saranno i test di sistema che dovranno essere sviluppati partendo dai requisiti di sistema individuati.

**Comment by Archetipo95** [comment]
Li abbiamo già, servono i test di integrazione, ma quelli si decide di farli solo quando avremo integrato tutte le parti in un unico prodotto.

Potresti controllare però i test di sistema che esistono e verificare se sono ok, se hanno senso. Sono nel PdQ in tabella 4.2
