### ISSUE TITLE
PdQ - Controllare se si possono aggiungere altre metriche e obiettivi

### ISSUE THREAD

**Issue by Archetipo95** [Spaghetti-Code-G6/swe-docs#102]
Controllare quelle già esistenti e confrontarle con gli altri documenti degli altri gruppi

**Comment by Archetipo95** [comment]
![image](https://user-images.githubusercontent.com/11798239/120000080-b83d6200-bfd2-11eb-8885-c0e6c6ae25be.png)
Per il momento nel PdQ ho csritto che controlliamo solo le linee di codice testate, ma volendo si potrebbero aggiungere anche gli altri parametri presenti in questa foto, tanto sono tutti automatici

**Comment by gpaparaz** [comment]
Siccome la issue riguarda solo le metriche, si può chiudere?

**Comment by Archetipo95** [comment]
I guess 🤷‍♂️
