### ISSUE TITLE
PdQ - Controllare se si possono aggiornare le fonti

### ISSUE THREAD

**Issue by Archetipo95** [Spaghetti-Code-G6/swe-docs#112]

**Comment by Archetipo95** [comment]
Si potrebbero aggiungere dei verbali interni, quando ci saranno, ad esempio, quello post valutazione o il riferimento della mail del prof sul versionamento

**Comment by gpaparaz** [comment]
Pensi sia meglio mettere due verbali distinti in cui abbiamo stabilito i due diversi modi di versionare, o la modalità stabilita ieri la faccio "confluire" in un precedente verbale?

**Comment by gpaparaz** [comment]
fatto, aggiornata sia la tabella, sia i riferimenti
