### ISSUE TITLE
Aggiungere a PdQ una sezione con riepilogo test

### ISSUE THREAD

**Issue by Archetipo95** [Spaghetti-Code-G6/swe-docs#81]
Esempio preso dagli Hexa;
![image](https://user-images.githubusercontent.com/11798239/114309677-483d5000-9ae8-11eb-8d83-33e4ef2c05c2.png)

**Comment by Archetipo95** [comment]
Sarebbe meglio aggiungere anche la quantità dei test oltre alla percentuale

**Comment by gpaparaz** [comment]
La quantità non è un dato necessario ad ottenere la percentuale finale?
